geometry_msgs/Transform sensor_to_world

uint32 height
uint32 width
uint32 stride
float32[] depths

float32 focal_length_x
float32 focal_length_y
float32 principal_point_x
float32 principal_point_y
---
bool success
