---
string tree_type

float64 resolution
float64 max_range
int64 num_nodes
int64 num_leaf_nodes
bool naive_scan_insertion
bool use_only_surface_voxels_for_score
string surface_voxels_filename
string binary_surface_voxels_filename

float64 occupancy_clamp_min
float64 occupancy_clamp_max
float64 occupancy_log_odds_clamp_min
float64 occupancy_log_odds_clamp_max
float64 occupancy_thres
float64 occupancy_log_odds_thres
float64 prob_hit
float64 prob_hit_log_odds
float64 prob_miss
float64 prob_miss_log_odds

float64 voxel_occupied_threshold
float64 voxel_free_threshold
float64 observation_count_saturation

geometry_msgs/Point score_bbox_min
geometry_msgs/Point score_bbox_max

float64 score
float64 normalized_score
float64 probabilistic_score
float64 normalized_probabilistic_score
