Ray[] rays
bool ignore_unknown_voxels
float32 max_range
bool override_thresholds
float32 occupancy_occupied_threshold
float32 occupancy_free_threshold
float32 observation_certainty_occupied_threshold
float32 observation_certainty_free_threshold
bool only_in_score_bounding_box
---
float32 elapsed_seconds
int32 num_hits_occupied
int32 num_hits_free
int32 num_hits_unknown
float32 expected_reward
sensor_msgs/PointCloud2 point_cloud
